### ISSUE TITLE
examples/synth.rs will not compile if its vst crate version does not match vst-gui's vst crate version

### ISSUE THREAD

**Issue by rokit** [vanderlokken/rust-vst-gui#2]
For example, I tried compiling `synth.rs` using `vst = "0.0.2"`, but `vst-gui` itself uses `vst = "0.0.1"`. This causes the Rust compiler to throw errors about traits not being implemented when they clearly are.

It might be better if you could make `synth.rs` not depend on `vst` at all so that only one version of it is ever used. I tried implementing this myself in `rust-vst-gui/lib.rs` with:

     pub use vst::buffer;
     pub use vst::editor;
     etc...

and then in `synth.rs`:

     use vst_gui::buffer::AudioBuffer;
     etc...

which works fine, but that still leaves the `plugin_main!` macro which I couldn't figure out.

**Comment by vanderlokken** [comment]
I updated the 'Cargo.toml' file. Now this library doesn't depend on some specific version of the 'vst' crate, so you can use it with vst 0.0.2.
