### ISSUE TITLE
Custom Width, Height for Window

### ISSUE THREAD

**Issue by Boscop** [vanderlokken/rust-vst-gui#3]
I built a VST using this crate (it needed a GUI to specify pitch ranges to block/pass-thru/map):

![image](https://user-images.githubusercontent.com/535593/48801114-d0e6a600-ed0b-11e8-9f1d-4f68046fa731.png)

I would like to be able to specify a custom width and height for the window, instead of using the default size of half of the physical screen:

https://github.com/vanderlokken/rust-vst-gui/blob/246cbd01cbefa9d5d52d184d439968f66c129bed/src/win32/gui.rs#L57-L58

If you want, I can implement this and do a PR?

**Comment by vanderlokken** [comment]
It should be pretty easy to implement I suppose. A PR would be welcome.
